#!/opt/pwn.college/python
import os
import sys
import subprocess
sys.path.append('/challenge')

def print_instructions():
    print("""
    In this challenge, you will exploit a vulnerability in version 2.3.4 of vsFTPd, otherwise known as the
    'smiley face' vulnerability. The FTP server should now be running. You can verify that is running by
    running the 'ss -antop' command and looking for something like '127.0.0.1:21', which
    indicates that the server is listening on TCP port 21.

    After you've verified that, use the 'nc' command (netcat) to connect to the server:
          nc 127.0.0.1 21

    Type 'USER test:)' and press enter. Notice the ':)' added to the end of the 'test' username.
    When it asks for a password, type 'PASS test' (the password can be anything).

    Then, in a new terminal, use the 'nc' command again to connect to port 6200, which should give you a root shell.
        nc 127.0.0.1 6200

    Type 'whoami' to verify that you are the root user. It should show 'root'.

    Congratulations! You have now exploited the vulnerability and can run commands as the root user, which means
    you can read the flag yourself!

    Inside the root shell, run 'cat /flag' to get your flag!
        cat /flag

    """)

def start_vsftpd():
    # Become root user to run vsftpd
    os.setuid(0)

    config_path = "/challenge/vsftpd-2.3.4/vsftpd.conf"
    subprocess.Popen(["vsftpd", config_path])

def print_flag():
	try:
		with open("/flag", "r") as f:
			print(f.read())
	except FileNotFoundError:
		print("Error: Flag file not found.")

def main():
    start_vsftpd()
    print_instructions()

if __name__ == "__main__":
    main()
