#!/opt/pwn.college/python
# Flask app for the sake of deploying the webpage needed
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def index():
	return render_template('index.html')

if __name__ == "__main__":
	app.run(debug=True)
